require "keymaps" 
-- require "tokyonight"
--require "tokyonight"
require "options" 
--require "hop-config"
--require "colorscheme"
require "lazy-config"
require "indentline-config"
require "lualine-config"
require "nvim-tree-config"
require "alpha-config"
require "autopairs-config"  
require "bufferline-config"
require "telescope-config"
require "toggleterm-config"
require "treesitter-config"
require "undotree-config"
require "whichkey"


